import "dotenv/config";
import { processScheduledQueue } from "@/lib/scheduler/worker-processor";
import { autoGenerateDailyContent } from "@/lib/scheduler/auto-generator";
import { closeBrowser } from "@/lib/platforms/browser-manager";
import { prisma } from "@/lib/prisma";

async function runCron() {
  console.log(`[Cron] Memulai pemrosesan antrean pada ${new Date().toISOString()}`);
  
  try {
    await processScheduledQueue();
    console.log("[Cron] Selesai memproses antrean.");
    
    // Jalankan pengecekan dan auto-generate
    await autoGenerateDailyContent();
  } catch (err) {
    console.error("[Cron] Error dalam queue processor:", err);
  } finally {
    await closeBrowser();
    await prisma.$disconnect();
  }
}

runCron().catch((err) => {
  console.error("[Cron] Fatal error:", err);
  process.exit(1);
});
