import { prisma } from "@/lib/prisma";
import { generateContentBatch, BusinessContext } from "@/lib/ai/gemini-content-generator";

export async function autoGenerateDailyContent(): Promise<void> {
  console.log(`[Auto-Generator] Memulai pengecekan akun sosial untuk auto-generate...`);

  try {
    // Cari semua social account yang aktif dan memiliki autoGenerateEnabled
    const accounts = await prisma.socialAccount.findMany({
      where: { 
        isActive: true,
        autoGenerateEnabled: true,
        autoGenerateContext: { not: undefined } // Prisma checks json validity
      }
    });

    if (accounts.length === 0) {
      console.log(`[Auto-Generator] Tidak ada akun yang mengaktifkan fitur ini.`);
      return;
    }

    const today = new Date();
    today.setHours(0, 0, 0, 0);

    const threeDaysFromNow = new Date(today);
    threeDaysFromNow.setDate(today.getDate() + 3);

    for (const account of accounts) {
      if (!account.autoGenerateContext) continue;
      
      const context = account.autoGenerateContext as any as BusinessContext;

      // Hitung post yang berstatus DRAFT, APPROVED, atau SCHEDULED dalam 3 hari ke depan
      const upcomingPosts = await prisma.post.count({
        where: {
          socialAccountId: account.id,
          status: { in: ["DRAFT", "APPROVED", "SCHEDULED"] },
          scheduledAt: { gte: today }
        }
      });

      // Jika kurang dari 3 post, berarti kita perlu top-up (generate baru)
      if (upcomingPosts < 3) {
        console.log(`[Auto-Generator] Akun ${account.id} (@${account.platformUsername}) memiliki stok konten menipis (${upcomingPosts}). Membuat konten baru...`);

        try {
          // Generate batch untuk 3 hari ke depan, 1 post per hari
          await generateContentBatch({
            userId: account.userId,
            socialAccountId: account.id,
            platform: account.platform,
            businessContext: context,
            days: 3,
            postsPerDay: 1,
            generateVariants: true,
          });
          console.log(`[Auto-Generator] ✅ Berhasil generate konten untuk @${account.platformUsername}`);
        } catch (err: any) {
          console.error(`[Auto-Generator] ❌ Gagal generate konten untuk @${account.platformUsername}:`, err.message);
        }
      } else {
        console.log(`[Auto-Generator] Akun @${account.platformUsername} memiliki stok konten aman (${upcomingPosts} posts).`);
      }
    }
  } catch (error) {
    console.error("[Auto-Generator] Error kritis dalam auto-generator:", error);
  }
}
